from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from llm.llm_provider import get_llm
from logger_config import logger

# used only for testing
# from processing.pdf_reader import read_pdf
# from processing.report_parser import parse_medical_report
# from agents.report_agent import report_agent
# from agents.explanation_agent import explanation_agent

def guidance_agent(state: dict):
    """
    LangGraph node for generating health guidance and lifestyle suggestions
    based on Medical Report Explanation.
    """

    try:
        logger.info("Starting Health Guidance Agent")

        # Get explanation generated by previous agent
        explanation = state.get("explanation", "")

        # initializing LLM
        llm = get_llm()

        if llm is None:
            logger.error("LLM initialization failed")
            state["guidance"] = "LLM initialization failed"
            return state
        
        # Prompt for generating health suggestions
        prompt = ChatPromptTemplate.from_template(
            """
You are a medical Wellness Assistant.

Based on the following explanation of a medical report,
provide simple and practical health guidance for the patient.

Explanation:
{explanation}

Instructions:

- Do NOT repeat or summarize the report result
- Directly provide helpful lifestyle guidance

- Include:
  • Healthy diet suggestions  
  • Physical activity recommendations  
  • Daily lifestyle habits  

- Keep the response short (4–6 lines)
- Write each suggestion on a new line

Rules:
- Do NOT diagnose diseases
- Do NOT prescribe medicine
- Do NOT repeat values or test results
- Use simple and easy-to-understand language
- Encourage consulting a doctor if needed
"""
        )

        # Creating Modern LCEL Pipeline
        chain = prompt | llm | StrOutputParser()

        logger.info("Generating Health Guidance using LLM")

        result = chain.invoke({
            "explanation" : explanation
        })

        # storing result in graph state
        state["guidance"] = result
        logger.info("Health Guidance Agent completed")
        return state
    
    except Exception as e:
        logger.error(f"Guidance Agent failed: {str(e)}")
        state["guidance"] = "Health guidance generation failed"
        return state
    

# testing the Guidnce Agent phase
# if __name__ == "__main__":

#     # path to the data
#     #sample_pdf = "sample_data/Sample Report.pdf"
#     sample_pdf = "sample_data/Glucose_report.pdf"

#     print("\nReading PDF..\n")

#     # Reading the PDF File
#     report_text = read_pdf(sample_pdf)

#     if not report_text:
#         print("failed to read report")
#         exit()

#     print("Parsing Medical Report..\n")

#     # Parse report values
#     medical_data = parse_medical_report(report_text)

#     if not medical_data:
#         print("No Medical data found")
#         exit()

#     # Initial LangGraph state
#     state = {
#         "medical_data" : medical_data
#     }

#     print("\nRunning Report Agent..\n")
#     state = report_agent(state)

#     print("\nRunning Explanation Agent..\n")
#     state = explanation_agent(state)

#     print("\nRunning Guidance Agent..\n")
#     state = guidance_agent(state)

#     print("\n------- Final Output -------\n")

#     print("\nAnalysis:\n")
#     print(state.get("analysis", "No analysis generated"))

#     print("\nExplanation:\n")
#     print(state.get("explanation", "No explanation generated"))

#     print("\nHealth Guidance:\n")
#     print(state.get("guidance", "No guidance generated"))